// Mocks generated by Mockito 5.4.6 from annotations
// in ueberboese_app/test/pages/device_events_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:ueberboese_app/models/device_event.dart' as _i4;
import 'package:ueberboese_app/services/management_api_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ManagementApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockManagementApiService extends _i1.Mock
    implements _i2.ManagementApiService {
  MockManagementApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration get timeout =>
      (super.noSuchMethod(
            Invocation.getter(#timeout),
            returnValue: _FakeDuration_0(this, Invocation.getter(#timeout)),
          )
          as Duration);

  @override
  _i3.Future<List<String>> fetchAccountSpeakers(
    String? apiUrl,
    String? accountId,
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAccountSpeakers, [
              apiUrl,
              accountId,
              username,
              password,
            ]),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<List<_i4.DeviceEvent>> fetchDeviceEvents(
    String? apiUrl,
    String? deviceId,
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDeviceEvents, [
              apiUrl,
              deviceId,
              username,
              password,
            ]),
            returnValue: _i3.Future<List<_i4.DeviceEvent>>.value(
              <_i4.DeviceEvent>[],
            ),
          )
          as _i3.Future<List<_i4.DeviceEvent>>);
}
